-- Función RPC para guardar shop_settings evitando problemas de schema cache
-- Esto permite que el frontend guarde settings sin depender del cache de PostgREST

CREATE OR REPLACE FUNCTION public.save_shop_settings(
    p_user_id uuid,
    p_shop_name text DEFAULT NULL,
    p_email text DEFAULT NULL,
    p_phone text DEFAULT NULL,
    p_phone2 text DEFAULT NULL,
    p_fax text DEFAULT NULL,
    p_city text DEFAULT NULL,
    p_postal_code text DEFAULT NULL,
    p_state text DEFAULT NULL,
    p_country text DEFAULT NULL,
    p_address text DEFAULT NULL,
    p_website text DEFAULT NULL,
    p_registration_number text DEFAULT NULL,
    p_currency text DEFAULT NULL,
    p_currency_symbol text DEFAULT NULL,
    p_tax_rate numeric DEFAULT NULL,
    p_tax_included boolean DEFAULT NULL,
    p_accounting_method text DEFAULT NULL,
    p_time_format text DEFAULT NULL,
    p_language text DEFAULT NULL,
    p_start_time text DEFAULT NULL,
    p_end_time text DEFAULT NULL,
    p_invoice_prefix text DEFAULT NULL,
    p_ticket_prefix text DEFAULT NULL,
    p_default_warranty text DEFAULT NULL,
    p_footer_text text DEFAULT NULL,
    p_receive_emails boolean DEFAULT NULL,
    p_restocking_fee boolean DEFAULT NULL,
    p_deposit_repairs boolean DEFAULT NULL,
    p_screen_timeout text DEFAULT NULL,
    p_decimal_places text DEFAULT NULL,
    p_timezone text DEFAULT NULL,
    p_price_format text DEFAULT NULL,
    p_iva_condition text DEFAULT NULL,
    p_logo_url text DEFAULT NULL,
    p_terms_text_es text DEFAULT NULL,
    p_terms_text_ar text DEFAULT NULL,
    p_invoice_show_terms boolean DEFAULT NULL,
    p_whatsapp_phone text DEFAULT NULL,
    p_qz_tray_port integer DEFAULT NULL,
    p_qz_tray_using_secure boolean DEFAULT NULL,
    p_qz_tray_certificate_pem text DEFAULT NULL,
    p_qz_tray_certificate_label text DEFAULT NULL,
    p_qz_tray_direct_invoice_print boolean DEFAULT NULL,
    p_smtp_host text DEFAULT NULL,
    p_smtp_port integer DEFAULT NULL,
    p_smtp_user text DEFAULT NULL,
    p_smtp_password text DEFAULT NULL,
    p_customer_notify_channels jsonb DEFAULT NULL,
    p_portal_enabled boolean DEFAULT NULL,
    p_portal_require_login boolean DEFAULT NULL,
    p_portal_show_diagnostic_notes boolean DEFAULT NULL,
    p_portal_allow_quote_approval boolean DEFAULT NULL,
    p_portal_show_invoices boolean DEFAULT NULL,
    p_ticket_repairs_settings jsonb DEFAULT NULL,
    p_panel_ui_mode text DEFAULT NULL,
    p_chat_enabled boolean DEFAULT NULL,
    p_security_controls jsonb DEFAULT NULL,
    p_alt_name text DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.shop_settings (
        user_id, shop_name, email, phone, phone2, fax, city, postal_code, state, country,
        address, website, registration_number, currency, currency_symbol, tax_rate,
        tax_included, accounting_method, time_format, language, start_time, end_time,
        invoice_prefix, ticket_prefix, default_warranty, footer_text, receive_emails,
        restocking_fee, deposit_repairs, screen_timeout, decimal_places, timezone,
        price_format, iva_condition, logo_url, terms_text_es, terms_text_ar,
        invoice_show_terms, whatsapp_phone, qz_tray_port, qz_tray_using_secure,
        qz_tray_certificate_pem, qz_tray_certificate_label, qz_tray_direct_invoice_print,
        smtp_host, smtp_port, smtp_user, smtp_password, customer_notify_channels,
        portal_enabled, portal_require_login, portal_show_diagnostic_notes,
        portal_allow_quote_approval, portal_show_invoices, ticket_repairs_settings,
        panel_ui_mode, chat_enabled, security_controls, alt_name, created_at, updated_at
    )
    VALUES (
        p_user_id, p_shop_name, p_email, p_phone, p_phone2, p_fax, p_city, p_postal_code,
        p_state, p_country, p_address, p_website, p_registration_number, p_currency,
        p_currency_symbol, p_tax_rate, p_tax_included, p_accounting_method, p_time_format,
        p_language, p_start_time, p_end_time, p_invoice_prefix, p_ticket_prefix,
        p_default_warranty, p_footer_text, p_receive_emails, p_restocking_fee,
        p_deposit_repairs, p_screen_timeout, p_decimal_places, p_timezone, p_price_format,
        p_iva_condition, p_logo_url, p_terms_text_es, p_terms_text_ar, p_invoice_show_terms,
        p_whatsapp_phone, p_qz_tray_port, p_qz_tray_using_secure, p_qz_tray_certificate_pem,
        p_qz_tray_certificate_label, p_qz_tray_direct_invoice_print, p_smtp_host, p_smtp_port,
        p_smtp_user, p_smtp_password, p_customer_notify_channels, p_portal_enabled,
        p_portal_require_login, p_portal_show_diagnostic_notes, p_portal_allow_quote_approval,
        p_portal_show_invoices, p_ticket_repairs_settings, p_panel_ui_mode, p_chat_enabled,
        p_security_controls, p_alt_name, NOW(), NOW()
    )
    ON CONFLICT (user_id) DO UPDATE SET
        shop_name = EXCLUDED.shop_name,
        email = EXCLUDED.email,
        phone = EXCLUDED.phone,
        phone2 = EXCLUDED.phone2,
        fax = EXCLUDED.fax,
        city = EXCLUDED.city,
        postal_code = EXCLUDED.postal_code,
        state = EXCLUDED.state,
        country = EXCLUDED.country,
        address = EXCLUDED.address,
        website = EXCLUDED.website,
        registration_number = EXCLUDED.registration_number,
        currency = EXCLUDED.currency,
        currency_symbol = EXCLUDED.currency_symbol,
        tax_rate = EXCLUDED.tax_rate,
        tax_included = EXCLUDED.tax_included,
        accounting_method = EXCLUDED.accounting_method,
        time_format = EXCLUDED.time_format,
        language = EXCLUDED.language,
        start_time = EXCLUDED.start_time,
        end_time = EXCLUDED.end_time,
        invoice_prefix = EXCLUDED.invoice_prefix,
        ticket_prefix = EXCLUDED.ticket_prefix,
        default_warranty = EXCLUDED.default_warranty,
        footer_text = EXCLUDED.footer_text,
        receive_emails = EXCLUDED.receive_emails,
        restocking_fee = EXCLUDED.restocking_fee,
        deposit_repairs = EXCLUDED.deposit_repairs,
        screen_timeout = EXCLUDED.screen_timeout,
        decimal_places = EXCLUDED.decimal_places,
        timezone = EXCLUDED.timezone,
        price_format = EXCLUDED.price_format,
        iva_condition = EXCLUDED.iva_condition,
        logo_url = EXCLUDED.logo_url,
        terms_text_es = EXCLUDED.terms_text_es,
        terms_text_ar = EXCLUDED.terms_text_ar,
        invoice_show_terms = EXCLUDED.invoice_show_terms,
        whatsapp_phone = EXCLUDED.whatsapp_phone,
        qz_tray_port = EXCLUDED.qz_tray_port,
        qz_tray_using_secure = EXCLUDED.qz_tray_using_secure,
        qz_tray_certificate_pem = EXCLUDED.qz_tray_certificate_pem,
        qz_tray_certificate_label = EXCLUDED.qz_tray_certificate_label,
        qz_tray_direct_invoice_print = EXCLUDED.qz_tray_direct_invoice_print,
        smtp_host = EXCLUDED.smtp_host,
        smtp_port = EXCLUDED.smtp_port,
        smtp_user = EXCLUDED.smtp_user,
        smtp_password = EXCLUDED.smtp_password,
        customer_notify_channels = EXCLUDED.customer_notify_channels,
        portal_enabled = EXCLUDED.portal_enabled,
        portal_require_login = EXCLUDED.portal_require_login,
        portal_show_diagnostic_notes = EXCLUDED.portal_show_diagnostic_notes,
        portal_allow_quote_approval = EXCLUDED.portal_allow_quote_approval,
        portal_show_invoices = EXCLUDED.portal_show_invoices,
        ticket_repairs_settings = EXCLUDED.ticket_repairs_settings,
        panel_ui_mode = EXCLUDED.panel_ui_mode,
        chat_enabled = EXCLUDED.chat_enabled,
        security_controls = EXCLUDED.security_controls,
        alt_name = EXCLUDED.alt_name,
        updated_at = NOW();
END;
$$;

-- Dar permisos para que usuarios autenticados puedan usar la función
GRANT EXECUTE ON FUNCTION public.save_shop_settings(uuid, text, text, text, text, text, text, text, text, text, text, text, text, text, text, numeric, boolean, text, text, text, text, text, text, text, text, text, boolean, boolean, boolean, text, text, text, text, text, text, text, text, text, boolean, text, integer, boolean, text, text, boolean, text, integer, text, text, jsonb, boolean, boolean, boolean, boolean, boolean, jsonb, text, boolean, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_shop_settings(uuid, text, text, text, text, text, text, text, text, text, text, text, text, text, text, numeric, boolean, text, text, text, text, text, text, text, text, text, boolean, boolean, boolean, text, text, text, text, text, text, text, text, text, boolean, text, integer, boolean, text, text, boolean, text, integer, text, text, jsonb, boolean, boolean, boolean, boolean, boolean, jsonb, text, boolean, jsonb, text) TO anon;

COMMENT ON FUNCTION public.save_shop_settings IS 'Guarda o actualiza shop_settings evitando problemas de schema cache de PostgREST';
